import os

GDRIVE_TOKEN_PATH = os.getenv("GDRIVE_TOKEN_PATH", "credentials/token.json")
GDRIVE_CLIENT_SECRETS_PATH = os.getenv("GDRIVE_CLIENT_SECRETS_PATH", "credentials/client_secret.json")
GDRIVE_UPLOAD_FOLDER_ID = os.getenv("GDRIVE_UPLOAD_FOLDER_ID", "")
GDRIVE_PROCESSING_FOLDER_ID = os.getenv("GDRIVE_PROCESSING_FOLDER_ID", "")
GDRIVE_COMPLETED_FOLDER_ID = os.getenv("GDRIVE_COMPLETED_FOLDER_ID", "")
GDRIVE_ARCHIVE_UPLOAD_FOLDER_ID = os.getenv("GDRIVE_ARCHIVE_UPLOAD_FOLDER_ID", "")
GDRIVE_COMPLETED_OUTPUT_FOLDER_ID = os.getenv("GDRIVE_COMPLETED_OUTPUT_FOLDER_ID", "")
GDRIVE_COMPLETED_LOGS_FOLDER_ID = os.getenv("GDRIVE_COMPLETED_LOGS_FOLDER_ID", "")
POLL_INTERVAL_SECONDS = int(os.getenv("POLL_INTERVAL_SECONDS", "30"))
NOMINATIM_ENABLED = os.getenv("NOMINATIM_ENABLED", "false").lower() == "true"
CONFIDENCE_THRESHOLD = float(os.getenv("CONFIDENCE_THRESHOLD", "0.6"))

ADDR_COLUMN_PREFIX = "ADDR"
IC_COLUMN = "ICNO"
NAME_COLUMN = "NAME"

EXCEL_MIMETYPES = [
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
]
